[files]
room_types = "data/room_types.json"
locks = "data/locks.json"
keys = "data/keys.json"
items = "data/items.json"
biomes = "data/biomes.json"

[game]
num_rooms = 18
# grid_size will be squared
grid_size = 5
autopickup = true
